/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author visitante
 */
public class _TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public _TelaPrincipal() {
        initComponents();
        DesktopManager.addWindow("principal", this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        consultaMenu = new javax.swing.JMenu();
        pesoConsultaMenuItem = new javax.swing.JMenuItem();
        alimentoConsultaMenuItem = new javax.swing.JMenuItem();
        registroConsultaMenuItem = new javax.swing.JMenuItem();
        cadastroMenu = new javax.swing.JMenu();
        usuarioCadastroMenuItem = new javax.swing.JMenuItem();
        pesoCadastroMenuItem = new javax.swing.JMenuItem();
        alimentoCadastroMenuItem = new javax.swing.JMenuItem();
        registroCadastroMenuItem = new javax.swing.JMenuItem();
        relatorioMenu = new javax.swing.JMenu();
        ajudaMenu = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        consultaMenu.setText("Consulta");

        pesoConsultaMenuItem.setText("Peso");
        pesoConsultaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoConsultaMenuItemActionPerformed(evt);
            }
        });
        consultaMenu.add(pesoConsultaMenuItem);

        alimentoConsultaMenuItem.setText("Alimento");
        alimentoConsultaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alimentoConsultaMenuItemActionPerformed(evt);
            }
        });
        consultaMenu.add(alimentoConsultaMenuItem);

        registroConsultaMenuItem.setText("Registro");
        consultaMenu.add(registroConsultaMenuItem);

        jMenuBar1.add(consultaMenu);

        cadastroMenu.setText("Cadastro");

        usuarioCadastroMenuItem.setText("Usuário");
        cadastroMenu.add(usuarioCadastroMenuItem);

        pesoCadastroMenuItem.setText("Peso");
        pesoCadastroMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoCadastroMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(pesoCadastroMenuItem);

        alimentoCadastroMenuItem.setText("Alimento");
        alimentoCadastroMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alimentoCadastroMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(alimentoCadastroMenuItem);

        registroCadastroMenuItem.setText("Registro");
        cadastroMenu.add(registroCadastroMenuItem);

        jMenuBar1.add(cadastroMenu);

        relatorioMenu.setText("Relatório");
        jMenuBar1.add(relatorioMenu);

        ajudaMenu.setText("Ajuda");

        jMenuItem7.setText("Sobre");
        ajudaMenu.add(jMenuItem7);

        jMenuBar1.add(ajudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesoConsultaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoConsultaMenuItemActionPerformed
        // TODO add your handling code here:
        TelaConsultaPeso.main(null);
    }//GEN-LAST:event_pesoConsultaMenuItemActionPerformed

    private void alimentoConsultaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alimentoConsultaMenuItemActionPerformed
        // TODO add your handling code here:
        TelaConsultaAlimento.main(null);
    }//GEN-LAST:event_alimentoConsultaMenuItemActionPerformed

    private void pesoCadastroMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoCadastroMenuItemActionPerformed
        // TODO add your handling code here:
        TelaCadastroPeso.main(null);
    }//GEN-LAST:event_pesoCadastroMenuItemActionPerformed

    private void alimentoCadastroMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alimentoCadastroMenuItemActionPerformed
        // TODO add your handling code here:
        _TelaCadastroAlimento.main(null);
    }//GEN-LAST:event_alimentoCadastroMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajudaMenu;
    private javax.swing.JMenuItem alimentoCadastroMenuItem;
    private javax.swing.JMenuItem alimentoConsultaMenuItem;
    private javax.swing.JMenu cadastroMenu;
    private javax.swing.JMenu consultaMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem pesoCadastroMenuItem;
    private javax.swing.JMenuItem pesoConsultaMenuItem;
    private javax.swing.JMenuItem registroCadastroMenuItem;
    private javax.swing.JMenuItem registroConsultaMenuItem;
    private javax.swing.JMenu relatorioMenu;
    private javax.swing.JMenuItem usuarioCadastroMenuItem;
    // End of variables declaration//GEN-END:variables
}
