/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.RelatorioController;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import model.RelatorioModel;
import session.SessionManager;
import util.JPAUtil;

/**
 *
 * @author visitante
 */
public class PrincipalView extends javax.swing.JFrame {

    private RelatorioModel model = new RelatorioModel();
    private RelatorioController controller = new RelatorioController(model);
    /**
     * Creates new form TelaPrincipal
     */
    public PrincipalView() {        
        init();        
        initComponents();        
        doLogin();
    }
    
    private void init() {
        new Thread(() -> {
        JPAUtil.createEntityManagerFactory();
        }).start();
    }

    private void doLogin() {
        if (SessionManager.getUsuarioLogado() == null) {
            new Thread(() -> {
                LoginView login = new LoginView(this, true);
                login.setLocationRelativeTo(null);
                login.setVisible(true);
            }).start();
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        manutencaoMenu = new javax.swing.JMenu();
        manutencaoAlimentoMenuItem = new javax.swing.JMenuItem();
        manutencaoRelatorioMenuItem = new javax.swing.JMenuItem();
        manutencaoDiarioMenuItem = new javax.swing.JMenuItem();
        manutencaoPesoMenuItem = new javax.swing.JMenuItem();
        ajudaMenu = new javax.swing.JMenu();
        sobreMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Calorias");

        manutencaoMenu.setMnemonic(KeyEvent.VK_C);
        manutencaoMenu.setText("Manutenção");

        manutencaoAlimentoMenuItem.setMnemonic('s');
        manutencaoAlimentoMenuItem.setText("Alimento");
        manutencaoAlimentoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manutencaoAlimentoMenuItemActionPerformed(evt);
            }
        });
        manutencaoMenu.add(manutencaoAlimentoMenuItem);

        manutencaoRelatorioMenuItem.setText("Relatório");
        manutencaoRelatorioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manutencaoRelatorioMenuItemActionPerformed(evt);
            }
        });
        manutencaoMenu.add(manutencaoRelatorioMenuItem);

        manutencaoDiarioMenuItem.setMnemonic('a');
        manutencaoDiarioMenuItem.setText("Diário");
        manutencaoDiarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manutencaoDiarioMenuItemActionPerformed(evt);
            }
        });
        manutencaoMenu.add(manutencaoDiarioMenuItem);

        manutencaoPesoMenuItem.setMnemonic('o');
        manutencaoPesoMenuItem.setText("Peso");
        manutencaoPesoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manutencaoPesoMenuItemActionPerformed(evt);
            }
        });
        manutencaoMenu.add(manutencaoPesoMenuItem);

        menuBar.add(manutencaoMenu);

        ajudaMenu.setMnemonic(KeyEvent.VK_A);
        ajudaMenu.setText("Ajuda");

        sobreMenuItem.setText("Sobre");
        sobreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreMenuItemActionPerformed(evt);
            }
        });
        ajudaMenu.add(sobreMenuItem);

        menuBar.add(ajudaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sobreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreMenuItemActionPerformed
        SobreView.main(null);
    }//GEN-LAST:event_sobreMenuItemActionPerformed

    private void manutencaoAlimentoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manutencaoAlimentoMenuItemActionPerformed
        ManutencaoAlimentoView frame;

        if (DesktopManager.contains(DesktopManager.MANUTENCAO_ALIMENTO_VIEW)) {
            frame = (ManutencaoAlimentoView) DesktopManager.get(DesktopManager.MANUTENCAO_ALIMENTO_VIEW);
            desktopPane.setSelectedFrame(frame);
            frame.pack();
        } else {
            frame = new ManutencaoAlimentoView();
            desktopPane.add(frame);
            DesktopManager.add(DesktopManager.MANUTENCAO_ALIMENTO_VIEW, frame);
        }
        frame.show();
    }//GEN-LAST:event_manutencaoAlimentoMenuItemActionPerformed

    private void manutencaoRelatorioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manutencaoRelatorioMenuItemActionPerformed
        ManutencaoRelatorioView frame;
        
        if (DesktopManager.contains(DesktopManager.MANUTENCAO_RELATORIO_VIEW)) {
            frame = (ManutencaoRelatorioView) DesktopManager.get(DesktopManager.MANUTENCAO_RELATORIO_VIEW);
            desktopPane.setSelectedFrame(frame);
            frame.pack();
        } else {
            frame = new ManutencaoRelatorioView();
            desktopPane.add(frame);
            DesktopManager.add(DesktopManager.MANUTENCAO_RELATORIO_VIEW, frame);
        }
        frame.show();
    }//GEN-LAST:event_manutencaoRelatorioMenuItemActionPerformed

    private void manutencaoDiarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manutencaoDiarioMenuItemActionPerformed
        ManutencaoDiarioView frame;
        
        if (DesktopManager.contains(DesktopManager.MANUTENCAO_DIARIO_VIEW)) {
            frame = (ManutencaoDiarioView) DesktopManager.get(DesktopManager.MANUTENCAO_DIARIO_VIEW);
            desktopPane.setSelectedFrame(frame);
            frame.pack();
        } else {
            frame = new ManutencaoDiarioView();
            desktopPane.add(frame);
            DesktopManager.add(DesktopManager.MANUTENCAO_DIARIO_VIEW, frame);
        }
        frame.show();
    }//GEN-LAST:event_manutencaoDiarioMenuItemActionPerformed

    private void manutencaoPesoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manutencaoPesoMenuItemActionPerformed
        ManutencaoPesoUsuarioView frame;

        if (DesktopManager.contains(DesktopManager.MANUTENCAO_PESO_VIEW)) {
            frame = (ManutencaoPesoUsuarioView) DesktopManager.get(DesktopManager.MANUTENCAO_PESO_VIEW);
            desktopPane.setSelectedFrame(frame);
            frame.pack();
        } else {
            frame = new ManutencaoPesoUsuarioView();
            desktopPane.add(frame);
            DesktopManager.add(DesktopManager.MANUTENCAO_PESO_VIEW, frame);
        }
        frame.show();
    }//GEN-LAST:event_manutencaoPesoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            PrincipalView principal = new PrincipalView();
            principal.setLocationRelativeTo(null);
            principal.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajudaMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem manutencaoAlimentoMenuItem;
    private javax.swing.JMenuItem manutencaoDiarioMenuItem;
    private javax.swing.JMenu manutencaoMenu;
    private javax.swing.JMenuItem manutencaoPesoMenuItem;
    private javax.swing.JMenuItem manutencaoRelatorioMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem sobreMenuItem;
    // End of variables declaration//GEN-END:variables

}
