/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import session.SessionManager;
import util.JPAUtil;

/**
 *
 * @author visitante
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public PrincipalView() {        
        init();
        initComponents();        
        doLogin();
    }
    
    private void init() {
        new Thread(() -> {
        JPAUtil.createEntityManagerFactory();
        }).start();
    }

    private void doLogin() {
        if (SessionManager.getUsuarioLogado() == null) {
            new Thread(() -> {
                LoginView login = new LoginView(this, true);
                login.setLocationRelativeTo(null);
                login.setVisible(true);
            }).start();
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        cadastroMenu = new javax.swing.JMenu();
        cadastroAlimentoMenuItem = new javax.swing.JMenuItem();
        cadastroRelatorioMenuItem = new javax.swing.JMenuItem();
        cadastroRefeiçãoMenuItem = new javax.swing.JMenuItem();
        manutencaoPesoUsuarioMenuItem = new javax.swing.JMenuItem();
        manutencaoUsuarioMenuItem = new javax.swing.JMenuItem();
        consultaMenu = new javax.swing.JMenu();
        consultaAlimentoMenuItem = new javax.swing.JMenuItem();
        consultaRelatorioMenuItem = new javax.swing.JMenuItem();
        consultaDiarioMenuItem = new javax.swing.JMenuItem();
        consultaPesoMenuItem = new javax.swing.JMenuItem();
        ajudaMenu = new javax.swing.JMenu();
        sobreMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Calorias");

        cadastroMenu.setMnemonic(KeyEvent.VK_M);
        cadastroMenu.setText("Manutenção");

        cadastroAlimentoMenuItem.setMnemonic('p');
        cadastroAlimentoMenuItem.setText("Alimento");
        cadastroAlimentoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlimentoMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(cadastroAlimentoMenuItem);

        cadastroRelatorioMenuItem.setMnemonic('t');
        cadastroRelatorioMenuItem.setText("Relatório");
        cadastroMenu.add(cadastroRelatorioMenuItem);

        cadastroRefeiçãoMenuItem.setMnemonic('d');
        cadastroRefeiçãoMenuItem.setText("Refeição");
        cadastroRefeiçãoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroRefeiçãoMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(cadastroRefeiçãoMenuItem);

        manutencaoPesoUsuarioMenuItem.setMnemonic('y');
        manutencaoPesoUsuarioMenuItem.setText("Peso Usuário");
        manutencaoPesoUsuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manutencaoPesoUsuarioMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(manutencaoPesoUsuarioMenuItem);

        manutencaoUsuarioMenuItem.setText("Usuário");
        cadastroMenu.add(manutencaoUsuarioMenuItem);

        menuBar.add(cadastroMenu);

        consultaMenu.setMnemonic(KeyEvent.VK_C);
        consultaMenu.setText("Consulta");

        consultaAlimentoMenuItem.setMnemonic('s');
        consultaAlimentoMenuItem.setText("Alimento");
        consultaAlimentoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaAlimentoMenuItemActionPerformed(evt);
            }
        });
        consultaMenu.add(consultaAlimentoMenuItem);

        consultaRelatorioMenuItem.setText("Relatório");
        consultaRelatorioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaRelatorioMenuItemActionPerformed(evt);
            }
        });
        consultaMenu.add(consultaRelatorioMenuItem);

        consultaDiarioMenuItem.setMnemonic('a');
        consultaDiarioMenuItem.setText("Diário");
        consultaDiarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaDiarioMenuItemActionPerformed(evt);
            }
        });
        consultaMenu.add(consultaDiarioMenuItem);

        consultaPesoMenuItem.setMnemonic('o');
        consultaPesoMenuItem.setText("Peso");
        consultaPesoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPesoMenuItemActionPerformed(evt);
            }
        });
        consultaMenu.add(consultaPesoMenuItem);

        menuBar.add(consultaMenu);

        ajudaMenu.setMnemonic(KeyEvent.VK_A);
        ajudaMenu.setText("Ajuda");

        sobreMenuItem.setText("Sobre");
        sobreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreMenuItemActionPerformed(evt);
            }
        });
        ajudaMenu.add(sobreMenuItem);

        menuBar.add(ajudaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void manutencaoPesoUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manutencaoPesoUsuarioMenuItemActionPerformed
        ManutencaoPesoUsuarioView view;

        if (DesktopManager.contains(DesktopManager.TELA_CADASTRO_PESO_USUARIO)) {
            view = (ManutencaoPesoUsuarioView) DesktopManager.get(DesktopManager.TELA_CADASTRO_PESO_USUARIO);
            desktopPane.setSelectedFrame(view);
            view.pack();
        } else {
            view = new ManutencaoPesoUsuarioView();
            desktopPane.add(view);
            DesktopManager.add(DesktopManager.TELA_CADASTRO_PESO_USUARIO, view);
        }
        view.show();
    }//GEN-LAST:event_manutencaoPesoUsuarioMenuItemActionPerformed

    private void cadastroAlimentoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlimentoMenuItemActionPerformed
        TelaCadastroAlimento frame;

        if (DesktopManager.contains(DesktopManager.TELA_CADASTRO_ALIMENTO)) {
            frame = (TelaCadastroAlimento) DesktopManager.get(DesktopManager.TELA_CADASTRO_ALIMENTO);
            desktopPane.setSelectedFrame(frame);
            frame.pack();
        } else {
            frame = new TelaCadastroAlimento();
            desktopPane.add(frame);
            DesktopManager.add(DesktopManager.TELA_CADASTRO_ALIMENTO, frame);
        }
        frame.show();
    }//GEN-LAST:event_cadastroAlimentoMenuItemActionPerformed

    private void cadastroRefeiçãoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroRefeiçãoMenuItemActionPerformed
        TelaCadastroRefeicao frame;

        if (DesktopManager.contains(DesktopManager.TELA_CADASTRO_REFEICAO)) {
            frame = (TelaCadastroRefeicao) DesktopManager.get(DesktopManager.TELA_CADASTRO_REFEICAO);
            desktopPane.setSelectedFrame(frame);
            frame.pack();
        } else {
            frame = new TelaCadastroRefeicao();
            desktopPane.add(frame);
            DesktopManager.add(DesktopManager.TELA_CADASTRO_REFEICAO, frame);
        }
        frame.show();
    }//GEN-LAST:event_cadastroRefeiçãoMenuItemActionPerformed

    private void sobreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreMenuItemActionPerformed
        TelaSobre.main(null);
    }//GEN-LAST:event_sobreMenuItemActionPerformed

    private void consultaAlimentoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaAlimentoMenuItemActionPerformed
        ManutencaoAlimentoView frame;

        if (DesktopManager.contains(DesktopManager.TELA_CONSULTA_ALIMENTO)) {
            frame = (ManutencaoAlimentoView) DesktopManager.get(DesktopManager.TELA_CONSULTA_ALIMENTO);
            desktopPane.setSelectedFrame(frame);
            frame.pack();
        } else {
            frame = new ManutencaoAlimentoView();
            desktopPane.add(frame);
            DesktopManager.add(DesktopManager.TELA_CONSULTA_ALIMENTO, frame);
        }
        frame.show();
    }//GEN-LAST:event_consultaAlimentoMenuItemActionPerformed

    private void consultaRelatorioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaRelatorioMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaRelatorioMenuItemActionPerformed

    private void consultaDiarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaDiarioMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaDiarioMenuItemActionPerformed

    private void consultaPesoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPesoMenuItemActionPerformed
        ManutencaoPesoUsuarioView frame;

        if (DesktopManager.contains(DesktopManager.TELA_CONSULTA_PESO)) {
            frame = (ManutencaoPesoUsuarioView) DesktopManager.get(DesktopManager.TELA_CONSULTA_PESO);
            desktopPane.setSelectedFrame(frame);
            frame.pack();
        } else {
            frame = new ManutencaoPesoUsuarioView();
            desktopPane.add(frame);
            DesktopManager.add(DesktopManager.TELA_CONSULTA_PESO, frame);
        }
        frame.show();
    }//GEN-LAST:event_consultaPesoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            PrincipalView principal = new PrincipalView();
            principal.setLocationRelativeTo(null);
            principal.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajudaMenu;
    private javax.swing.JMenuItem cadastroAlimentoMenuItem;
    private javax.swing.JMenu cadastroMenu;
    private javax.swing.JMenuItem cadastroRefeiçãoMenuItem;
    private javax.swing.JMenuItem cadastroRelatorioMenuItem;
    private javax.swing.JMenuItem consultaAlimentoMenuItem;
    private javax.swing.JMenuItem consultaDiarioMenuItem;
    private javax.swing.JMenu consultaMenu;
    private javax.swing.JMenuItem consultaPesoMenuItem;
    private javax.swing.JMenuItem consultaRelatorioMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem manutencaoPesoUsuarioMenuItem;
    private javax.swing.JMenuItem manutencaoUsuarioMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem sobreMenuItem;
    // End of variables declaration//GEN-END:variables

}
