/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import session.SessionManager;

/**
 *
 * @author visitante
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        System.out.println("TESTE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        consultaMenu = new javax.swing.JMenu();
        consultaAlimentoMenuItem = new javax.swing.JMenuItem();
        consultaRelatorioMenuItem = new javax.swing.JMenuItem();
        consultaDiarioMenuItem = new javax.swing.JMenuItem();
        consultaPesoMenuItem = new javax.swing.JMenuItem();
        cadastroMenu = new javax.swing.JMenu();
        cadastroAlimentoMenuItem = new javax.swing.JMenuItem();
        cadastroRelatorioMenuItem = new javax.swing.JMenuItem();
        cadastroRefeiçãoMenuItem = new javax.swing.JMenuItem();
        cadastroPesoMenuItem = new javax.swing.JMenuItem();
        ajudaMenu = new javax.swing.JMenu();
        sobreMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Calorias");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        consultaMenu.setMnemonic('f');
        consultaMenu.setText("Consulta");

        consultaAlimentoMenuItem.setMnemonic('s');
        consultaAlimentoMenuItem.setText("Alimento");
        consultaMenu.add(consultaAlimentoMenuItem);

        consultaRelatorioMenuItem.setText("Relatório");
        consultaMenu.add(consultaRelatorioMenuItem);

        consultaDiarioMenuItem.setMnemonic('a');
        consultaDiarioMenuItem.setText("Diário");
        consultaMenu.add(consultaDiarioMenuItem);

        consultaPesoMenuItem.setMnemonic('o');
        consultaPesoMenuItem.setText("Peso");
        consultaMenu.add(consultaPesoMenuItem);

        menuBar.add(consultaMenu);

        cadastroMenu.setMnemonic('e');
        cadastroMenu.setText("Cadastro");

        cadastroAlimentoMenuItem.setMnemonic('p');
        cadastroAlimentoMenuItem.setText("Alimento");
        cadastroAlimentoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlimentoMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(cadastroAlimentoMenuItem);

        cadastroRelatorioMenuItem.setMnemonic('t');
        cadastroRelatorioMenuItem.setText("Relatório");
        cadastroMenu.add(cadastroRelatorioMenuItem);

        cadastroRefeiçãoMenuItem.setMnemonic('d');
        cadastroRefeiçãoMenuItem.setText("Refeição");
        cadastroMenu.add(cadastroRefeiçãoMenuItem);

        cadastroPesoMenuItem.setMnemonic('y');
        cadastroPesoMenuItem.setText("Peso");
        cadastroPesoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPesoMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(cadastroPesoMenuItem);

        menuBar.add(cadastroMenu);

        ajudaMenu.setText("Ajuda");

        sobreMenuItem.setText("Sobre");
        ajudaMenu.add(sobreMenuItem);

        menuBar.add(ajudaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroPesoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPesoMenuItemActionPerformed
        // TODO add your handling code here:

        TelaCadastroPeso frame;

        if (DesktopManager.contains(DesktopManager.TELA_CADASTRO_PESO)) {
            frame = (TelaCadastroPeso) DesktopManager.get(DesktopManager.TELA_CADASTRO_PESO);
            desktopPane.setSelectedFrame(frame);
            frame.pack();
        } else {
            frame = new TelaCadastroPeso();
            desktopPane.add(frame);
            DesktopManager.add(DesktopManager.TELA_CADASTRO_PESO, frame);
        }
        frame.show();
    }//GEN-LAST:event_cadastroPesoMenuItemActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (SessionManager.getUsuarioLogado() == null) {
            TelaLogin login = new TelaLogin(this, true);
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        }
    }//GEN-LAST:event_formWindowActivated

    private void cadastroAlimentoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlimentoMenuItemActionPerformed
        TelaCadastroAlimento frame;
        
        if (DesktopManager.contains(DesktopManager.TELA_CADASTRO_ALIMENTO)) {
            frame = (TelaCadastroAlimento) DesktopManager.get(DesktopManager.TELA_CADASTRO_ALIMENTO);
            desktopPane.setSelectedFrame(frame);
            frame.pack();
        } else {
            frame = new TelaCadastroAlimento();
            desktopPane.add(frame);
            DesktopManager.add(DesktopManager.TELA_CADASTRO_ALIMENTO, frame);
        }
        frame.show();
    }//GEN-LAST:event_cadastroAlimentoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            TelaPrincipal principal = new TelaPrincipal();
            principal.setLocationRelativeTo(null);
            principal.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajudaMenu;
    private javax.swing.JMenuItem cadastroAlimentoMenuItem;
    private javax.swing.JMenu cadastroMenu;
    private javax.swing.JMenuItem cadastroPesoMenuItem;
    private javax.swing.JMenuItem cadastroRefeiçãoMenuItem;
    private javax.swing.JMenuItem cadastroRelatorioMenuItem;
    private javax.swing.JMenuItem consultaAlimentoMenuItem;
    private javax.swing.JMenuItem consultaDiarioMenuItem;
    private javax.swing.JMenu consultaMenu;
    private javax.swing.JMenuItem consultaPesoMenuItem;
    private javax.swing.JMenuItem consultaRelatorioMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem sobreMenuItem;
    // End of variables declaration//GEN-END:variables

}
