/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import session.SessionManager;

/**
 *
 * @author visitante
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        System.out.println("TESTE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cadastroUsuarioMenuItem = new javax.swing.JMenuItem();
        cadastroPesoMenuItem = new javax.swing.JMenuItem();
        cadastroAlimentoMenuItem = new javax.swing.JMenuItem();
        cadastroRegistroMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Calorias");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("Consulta");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Peso");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Alimento");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Registro");
        fileMenu.add(saveAsMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Cadastro");

        cadastroUsuarioMenuItem.setMnemonic('t');
        cadastroUsuarioMenuItem.setText("Usuário");
        editMenu.add(cadastroUsuarioMenuItem);

        cadastroPesoMenuItem.setMnemonic('y');
        cadastroPesoMenuItem.setText("Peso");
        cadastroPesoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPesoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cadastroPesoMenuItem);

        cadastroAlimentoMenuItem.setMnemonic('p');
        cadastroAlimentoMenuItem.setText("Alimento");
        cadastroAlimentoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlimentoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cadastroAlimentoMenuItem);

        cadastroRegistroMenuItem.setMnemonic('d');
        cadastroRegistroMenuItem.setText("Registro");
        editMenu.add(cadastroRegistroMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Relatorio");
        menuBar.add(helpMenu);

        jMenu1.setText("Ajuda");

        jMenuItem1.setText("Sobre");
        jMenu1.add(jMenuItem1);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroPesoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPesoMenuItemActionPerformed
        // TODO add your handling code here:

        TelaCadastroPeso frame;

        if (DesktopManager.contains(DesktopManager.TELA_CADASTRO_PESO)) {
            frame = (TelaCadastroPeso) DesktopManager.get(DesktopManager.TELA_CADASTRO_PESO);
            desktopPane.setSelectedFrame(frame);
            frame.pack();
        } else {
            frame = new TelaCadastroPeso();
            desktopPane.add(frame);
            DesktopManager.add(DesktopManager.TELA_CADASTRO_PESO, frame);
        }
        frame.show();
    }//GEN-LAST:event_cadastroPesoMenuItemActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (SessionManager.getUsuarioLogado() == null) {
            TelaLogin login = new TelaLogin(this, true);
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        }
    }//GEN-LAST:event_formWindowActivated

    private void cadastroAlimentoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlimentoMenuItemActionPerformed
        TelaCadastroAlimento frame;
        
        if (DesktopManager.contains(DesktopManager.TELA_CADASTRO_ALIMENTO)) {
            frame = (TelaCadastroAlimento) DesktopManager.get(DesktopManager.TELA_CADASTRO_ALIMENTO);
            desktopPane.setSelectedFrame(frame);
            frame.pack();
        } else {
            frame = new TelaCadastroAlimento();
            desktopPane.add(frame);
            DesktopManager.add(DesktopManager.TELA_CADASTRO_ALIMENTO, frame);
        }
        frame.show();
    }//GEN-LAST:event_cadastroAlimentoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            TelaPrincipal principal = new TelaPrincipal();
            principal.setLocationRelativeTo(null);
            principal.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastroAlimentoMenuItem;
    private javax.swing.JMenuItem cadastroPesoMenuItem;
    private javax.swing.JMenuItem cadastroRegistroMenuItem;
    private javax.swing.JMenuItem cadastroUsuarioMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
